---
title: "Assignment Validation"
author: "WSP | Parsons Brinckerhoff"
output: html_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(cache=FALSE,echo=FALSE,
                      message=FALSE,warning=FALSE,error=TRUE)
options(scipen=999) # removes sci notation
```


```{r setup}
library(outviz)
library(dplyr)
library(knitr)
library(ggplot2)
library(tcadr)
```


```{r area_type}
# Use these two variables to specify the names of your volume and
# count fields.  These will be used in the standard plots.
volume_var <- "DailyFlow"
count_var <- "DailyCount"


# Read in the links table.  readr or tcadr could be used here.
links <-
  readr::read_csv("links.csv") %>%
  rename(
    facility_group = HCMType,
    area_type = AreaType,
    screenline = Screenline
  ) %>%
  filter(!(is.na(DailyCount))) %>%
  mutate(
    facility_group = factor(
      facility_group,
      labels = c(
        "Freeway", "MLHighway", "TLHighway", "PrArterial",
        "MinArterial", "Collector"
      )
    ),
    area_name = factor(
      area_type,
      labels = c("Urban", "Suburban", "Rural")
    )
  )
```

```{r targets}
rmse_facility_group <- data_frame(
  facility_group = c("Freeway", "MLHighway", "TLHighway", "PrArterial",
        "MinArterial", "Collector", "Total"),
  Target = c(25, 35, 50, 50, 65, 100, 40)
)

flow_volume_group <- data_frame(
  `Volume_Group` = c(
    "0 - 5000", "5000 - 10000", "10000 - 15000", "15000 - 20000",
    "20000 - 30000", "> 30000", "Total"),
  Target = c( 100, 45, 35, 30, 27, 25, 10 )
)

rmse_volume_group <- data_frame(
  `Volume_Group` = c(
    "0 - 5000", "5000 - 10000", "10000 - 15000", "15000 - 20000",
    "20000 - 30000", "30000 - 50000", "50000 - 60000",
    "> 60000", "Total"),
  Target = c(100, 45, 35, 30, 27, 25, 20, 19, 40)
)
```

```{r validation}
plot_validation(links, volume_var, count_var, show_lm = TRUE)
plot_validation(links, volume_var, count_var, show_lm = TRUE) +
  facet_wrap(~ area_name, scales = "free")
plot_validation(links, volume_var, count_var) +
  facet_wrap(~ facility_group)
```

```{r mdd}
plot_mdd(links, volume_var, count_var)
plot_mdd(links, volume_var, count_var, color_field = "facility_group")
```

```{r rmse}
link_stats_table(links, volume_var, count_var, group_field = "facility_group",
                 type = "rmse") %>%
  left_join(rmse_facility_group, by = "facility_group") %>%
  kable(digits = 2, caption = "RMSE by Facility Group")

link_stats_table(links, volume_var, count_var, group_field = "area_name",
                 type = "rmse") %>%
  kable(digits = 2, caption = "RMSE by Area Type")

link_stats_table(links, volume_var, count_var, group_field = volume_var,
                 volume_breaks = c(0, 5, 10, 15, 20, 30, 50, 60, Inf), type = "rmse") %>%
  left_join(rmse_volume_group, by = "Volume_Group") %>%
  kable(digits = 2, caption = "RMSE by Volume Group")
```

```{r flow}
link_stats_table(links, volume_var, count_var, group_field = "facility_group",
                 type = "flow") %>%
  kable(digits = 2, caption = "Total Flow by Facility Group")

link_stats_table(links, volume_var, count_var, group_field = volume_var,
                 volume_breaks = c(0, 5, 10, 15, 20, 30, Inf), type = "flow") %>%
  left_join(flow_volume_group, by = "Volume_Group") %>%
  kable(digits = 2, caption = "Total Flow by Volume Group")

link_stats_table(links, volume_var, count_var, group_field = "area_name",
                 type = "flow") %>%
  kable(digits = 2, caption = "Total Flow by Area Type")

link_stats_table(links %>% filter(screenline != 0),
                 volume_var, count_var, group_field = "screenline", type = "flow") %>%
  mutate(Target = 10) %>%
  kable(digits = 2, caption = "Total Flow by Volume Group")
```

```{r link_targets}
volString <- paste0(volume_var, " > 10000")
link_targets(links, volume_var, count_var,
             "facility_group == 'Expressway'", volString) %>%
  kable(digits = 2, caption = "Individual Link Targets")
```
